name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jdorsman
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe your issue. What is happening?
  - type: input
    id: game-version
    attributes:
      label: What version of the game are you on?
      placeholder: You can use the following command in chat to find out `/run print((select(1, GetBuildInfo())))` (The command may show you a warning asking if you want to run potentially dangerous scripts, if you never did a `/run` before and confirmed this already)
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description:  Please describe what steps you took for the issue to encounter. For example 1. Login to the game\n2. Type `/tradetracker` in chat\n3. Click the Sell tab\n4. An error appears saying ....
  - type: checkboxes
    id: isolation
    attributes:
      label: Isolation
      description: To determine if there might be a conflict with another one of your addons, have you tried disabling all addons except TradeTracker?
      options:
        - label: Yes, the issue occurs with only TradeTracker enabled
        - label: No, I have not disabled my other addons
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: If there's anything else you'd like to mention about the bug, you can do so here.
